SUBGROUPS_DROPDOWN_ID: str = "subgroups-dropdown"
PLOT_SUBGROUPS_BUTTON_ID: str = "plot-subgroups-button"
MAIN_LAYOUT_ID: str = "main-layout"
SUBGROUPS_PLOT_ID: str = "subgroups-plot"
DENDOGRAM_PLOT_ID: str = "dendogram-plot"